name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [gitlab_config, gitlab_approvers, gitflood]
    
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: check --diff ${{ matrix.project }}

      - name: Run ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff ${{ matrix.project }}